"""commit

Revision ID: 6b566b72eeb1
Revises: 
Create Date: 2020-03-30 21:24:28.790113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b566b72eeb1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=32), nullable=True),
    sa.Column('time', sa.String(length=16), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pressure', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_measurement_date'), 'measurement', ['date'], unique=False)
    op.create_index(op.f('ix_measurement_time'), 'measurement', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurement_time'), table_name='measurement')
    op.drop_index(op.f('ix_measurement_date'), table_name='measurement')
    op.drop_table('measurement')
    # ### end Alembic commands ###
